-- Tablespace
CREATE SMALLFILE TABLESPACE PRUEBA_TABLESPACE DATAFILE '?/PRUEBA.dbf' SIZE 500M
AUTOEXTEND ON NEXT 50M MAXSIZE 1000M
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;

-- Usuario aplicación propietario
CREATE USER "PRUEBA_OWN" IDENTIFIED BY "prueba"
DEFAULT TABLESPACE "PRUEBA_TABLESPACE"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "PRUEBA_TABLESPACE"
account unlock;

-- Roles de la aplicación 
-- Se crea el ROL
CREATE ROLE ROL_APLICACION_PRUEBA;
-- Se le conceden los permisos necesarios para poder realizar las ejecuciones de creación del modelo
GRANT CONNECT TO ROL_APLICACION_PRUEBA;
GRANT RESOURCE TO ROL_APLICACION_PRUEBA;
GRANT CREATE VIEW TO ROL_APLICACION_PRUEBA;

-- OTORGA EL ROL AL USUARIO DE APLICACION
GRANT ROL_APLICACION_PRUEBA TO PRUEBA_OWN;

-- Usuario de la aplicación
CREATE USER "PRUEBA_USR" IDENTIFIED BY "prueba"
DEFAULT TABLESPACE "PRUEBA_TABLESPACE"
TEMPORARY TABLESPACE "TEMP"
account unlock;

-- 